name: Generate Release Notes

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: ~

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    env:
      DASHSCOPE_API_KEY: ${{ secrets.DASHSCOPE_API_KEY }}
      MODEL_NAME: ${{ secrets.MODEL_NAME }}
      MODEL_SERVER: ${{ secrets.MODEL_SERVER }}
      RELEASE_VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout Higress code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Clone GitHub MCP Server
        run: |
          git clone https://github.com/github/github-mcp-server.git
          cd github-mcp-server
          go build -o ../github-mcp-serve ./cmd/github-mcp-server
          cd ..
          chmod u+x github-mcp-serve

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Clone Higress Report Agent
        run: |
          git clone https://github.com/higress-group/higress-report-agent.git
          mv github-mcp-serve higress-report-agent/

      - name: Create Release Report Script
        run: |
          cat > generate_release_report.sh << 'EOF'
          #!/bin/bash
          # Script to generate release notes for Higress projects

          echo "Fetching GitHub generated release notes for ${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}..."
          curl -L \
              "https://github.com/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}/releases/tag/${RELEASE_VERSION}" \
              -o release_page.html

          echo "Extracting PR numbers from ${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME} release notes..."
          PR_NUMS=$(cat release_page.html | grep -o "/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}/pull/[0-9]*" | grep -o "[0-9]*$" | sort -n | uniq | tr '\n' ',')
          PR_NUMS=${PR_NUMS%,}

          echo "Identifying important PRs..."
          IMPORTANT_PR_NUMS=$(cat release_page.html | grep -o "<strong>.*/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}/pull/[0-9]*.*</strong>" | grep -o "pull/[0-9]*" | grep -o "[0-9]*" | sort -n | uniq | tr '\n' ',')
          IMPORTANT_PR_NUMS=${IMPORTANT_PR_NUMS%,}

          rm release_page.html

          echo "Extracted PR numbers for ${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}: ${PR_NUMS}"
          echo "Important PR numbers: ${IMPORTANT_PR_NUMS}"

          echo "Generating detailed release notes for ${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}..."
          cd higress-report-agent
          pip install uv
          uv sync
          if [ -n "${IMPORTANT_PR_NUMS}" ]; then
              uv run report_main.py --mode 2 --choice 2 --pr_nums ${PR_NUMS} --important_prs ${IMPORTANT_PR_NUMS}
          else
              uv run report_main.py --mode 2 --choice 2 --pr_nums ${PR_NUMS}
          fi
          cp report.md ../
          cp report.EN.md ../
          cd ..

          # 去除版本号前缀v
          CLEAN_VERSION=${RELEASE_VERSION#v}

          echo "Creating release notes directory for version ${RELEASE_VERSION}..."
          mkdir -p release-notes/${CLEAN_VERSION}

          echo "# ${REPORT_TITLE}" >>release-notes/${CLEAN_VERSION}/README_ZH.md
          sed 's/# Release Notes//' report.md >>release-notes/${CLEAN_VERSION}/README_ZH.md
          echo "\n" >>release-notes/${CLEAN_VERSION}/README_ZH.md

          echo "# ${REPORT_TITLE}" >>release-notes/${CLEAN_VERSION}/README.md
          sed 's/# Release Notes//' report.EN.md >>release-notes/${CLEAN_VERSION}/README.md
          echo "\n" >>release-notes/${CLEAN_VERSION}/README_ZH.md

          rm report.md
          rm report.EN.md
          echo "${REPORT_TITLE} release notes saved to release-notes/${CLEAN_VERSION}/"

          EOF
          chmod +x generate_release_report.sh

      - name: Generate Release Notes for Higress Core
        env:
          GITHUB_REPO_OWNER: alibaba
          GITHUB_REPO_NAME: higress
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPORT_TITLE: Higress Core
        run: |
          bash generate_release_report.sh

      - name: Generate Release Notes for Higress Console
        env:
          GITHUB_REPO_OWNER: higress-group
          GITHUB_REPO_NAME: higress-console
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPORT_TITLE: Higress Console
        run: |
          bash generate_release_report.sh

      - name: Clean
        run: |
          rm generate_release_report.sh
          rm -rf higress-report-agent
          rm -rf github-mcp-server

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add release notes"
          branch: add-release-notes
          title: "Add release notes"
          body: |
            This PR adds release notes.

            - Automatically generated by GitHub Actions
          labels: release notes, automated
          base: main
